title: Amy Takeuchi # your name (or website title) here
logo: <img src="/images/Amy_head.png" width="100" height="200" alt="Logo">
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven problem solver with a background in Analytics, Business Intelligence, and Consulting. Proficient in SQL, Python, and R. 
  <br><br>
  MSc from London School of Economics in International Political Economy and International Finance.
  <br><br>
  <a href="https://www.linkedin.com/in/asami-takeuchi/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
